version: "3"
services:
  nginx:
    image: nginx
    build: ./nginx
    container_name: nginx_docker
    volumes:
      - /deploy:/deploy
      - /deploy/web_docker/nginx/conf.d:/etc/nginx/conf.d
    restart: always
  web:
    image: web
    build: ./web
    container_name: web_server_docker
    restart: always
    volumes:
      - /deploy/web_docker/web/node_server:/node_server
    ports:
      - "20000:20000"